openapi: 3.0.0
info:
  title: Ollama Receiver API
  version: 1.0.0
  description: API that acts as a midpoint between the web app and the LLM, providing skill recommendations.

paths:
  /request_skills:
    post:
      summary: Send user skills and job history to get recommended skills for a given job.
      operationId: reciever_app.request_skills
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                company:
                  type: string
                responsibilities:
                  type: string
                skills:
                  type: array
                  items:
                    type: string
              required:
                - title
                - company
                - responsibilities
                - skills
      responses:
        '200':
          description: A list of recommended skills for the target job
          content:
            application/json:
              schema:
                type: object
                properties:
                  recommended_skills:
                    type: array
                    items:
                      type: string
              example:
                recommended_skills: ["Project Management", "Leadership", "Data Analysis"]
        '400':
          description: Bad request - Invalid data format
        '500':
          description: Server error - Unable to process request